version: '3.7'
services:
  minio:
    hostname: minio
    image: 'mheers/minio-server:latest'
    build: .
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
